import { Activity } from "@/types";

export const mockActivities: Activity[] = [
  {
    id: "1",
    name: "Tiny Brushstrokes Studio",
    type: "Arts & Crafts",
    description:
      "Tiny Brushstrokes is a beloved local art studio offering weekly painting and mixed-media classes for children. Each session introduces kids to a new technique — from watercolours to collage — led by professional teaching artists in a relaxed, encouraging environment. All materials are provided. No experience needed — just curiosity and enthusiasm.",
    imageUrl: "https://picsum.photos/seed/artclass/1200/500",
    address: "243 Clement St, San Francisco, CA 94118",
    distanceMiles: 1.2,
    driveMinutes: 12,
    ageMin: 4,
    ageMax: 12,
    cost: 18,
    costLabel: "$18 / session",
    tags: ["Arts & Crafts", "Painting", "Mixed media", "Instructor-led", "Indoor", "Beginner-friendly"],
    schedule: "Sat & Sun, 10am – 4pm",
    duration: "90 minutes",
    lat: 37.7831,
    lng: -122.4639,
  },
  {
    id: "2",
    name: "Golden Gate Nature Trail",
    type: "Outdoors",
    description:
      "A stunning family-friendly trail winding through Golden Gate Park's western edge. Ideal for children of all ages, with plenty of interesting flora, wildlife spotting opportunities, and open meadows to run around in. Picnic tables and restrooms available along the route.",
    imageUrl: "https://picsum.photos/seed/park2/1200/500",
    address: "Golden Gate Park, San Francisco, CA 94122",
    distanceMiles: 2.8,
    driveMinutes: 8,
    ageMin: 0,
    ageMax: null,
    cost: null,
    costLabel: "Free",
    tags: ["Outdoors", "Nature", "Walking", "Family", "Dogs welcome"],
    schedule: "Open daily, sunrise to sunset",
    duration: "1–3 hours",
    lat: 37.7694,
    lng: -122.4862,
  },
  {
    id: "3",
    name: "Exploratorium Kids Lab",
    type: "Science",
    description:
      "An interactive science museum that sparks curiosity in kids through hands-on experiments and exhibits. The Kids Lab area is designed specifically for children aged 6–14, with guided experiments in chemistry, physics, and biology. Staff scientists are on hand to explain concepts in fun, engaging ways.",
    imageUrl: "https://picsum.photos/seed/science3/1200/500",
    address: "Pier 15, The Embarcadero, San Francisco, CA 94111",
    distanceMiles: 3.1,
    driveMinutes: 15,
    ageMin: 6,
    ageMax: 14,
    cost: 12,
    costLabel: "$12 entry",
    tags: ["Science", "Interactive", "Museum", "STEM", "Indoor"],
    schedule: "Tue–Sun, 10am – 5pm",
    duration: "2–3 hours",
    lat: 37.8009,
    lng: -122.3977,
  },
  {
    id: "4",
    name: "Aqua Cubs Swimming Class",
    type: "Swimming",
    description:
      "Structured swimming lessons for young children aged 3–8, taught by certified instructors in a heated indoor pool. Classes focus on water confidence, basic strokes, and safety. Small group sizes ensure every child gets personal attention.",
    imageUrl: "https://picsum.photos/seed/swim4/1200/500",
    address: "1 Morrell St, San Francisco, CA 94107",
    distanceMiles: 0.9,
    driveMinutes: 5,
    ageMin: 3,
    ageMax: 8,
    cost: 22,
    costLabel: "$22 / lesson",
    tags: ["Swimming", "Lessons", "Water safety", "Indoor pool", "Small groups"],
    schedule: "Mon / Wed / Fri, 9am – 12pm",
    duration: "45 minutes",
    lat: 37.7652,
    lng: -122.4093,
  },
  {
    id: "5",
    name: "Little Composers Workshop",
    type: "Music",
    description:
      "A creative music programme for children aged 5–11 that combines instrument exploration, rhythm games, and simple songwriting. Children rotate through piano, ukulele, and percussion in each session, developing musicality and confidence in a playful group setting.",
    imageUrl: "https://picsum.photos/seed/music5/1200/500",
    address: "820 Valencia St, San Francisco, CA 94110",
    distanceMiles: 4.0,
    driveMinutes: 18,
    ageMin: 5,
    ageMax: 11,
    cost: 30,
    costLabel: "$30 / session",
    tags: ["Music", "Piano", "Ukulele", "Percussion", "Group class"],
    schedule: "Sat, 9am – 12pm",
    duration: "60 minutes",
    lat: 37.7588,
    lng: -122.4213,
  },
  {
    id: "6",
    name: "SF Zoo Junior Ranger Day",
    type: "Animals",
    description:
      "A specially curated zoo experience for young animal enthusiasts. Children join a Junior Ranger guide for a 2-hour tour of the zoo, learning about animal habitats, conservation, and getting close to some of the zoo's friendliest residents. Perfect for curious kids who love nature.",
    imageUrl: "https://picsum.photos/seed/zoo6/1200/500",
    address: "1 Zoo Rd, San Francisco, CA 94132",
    distanceMiles: 5.2,
    driveMinutes: 22,
    ageMin: 4,
    ageMax: 12,
    cost: 16,
    costLabel: "$16 entry",
    tags: ["Animals", "Zoo", "Conservation", "Guided tour", "Outdoor"],
    schedule: "Every weekend, 10am & 2pm",
    duration: "2 hours",
    lat: 37.7325,
    lng: -122.5008,
  },
];
